import { readFile, stat } from "node:fs/promises";
import { resolve } from "node:path";

const projectRoot = resolve(import.meta.dirname, "..");
const requiredArtifacts = ["main.js", "manifest.json", "styles.css"];
const minimumArtifactSizes = {
  "main.js": 1024,
  "manifest.json": 64,
  "styles.css": 64
};

const manifest = await readJson("manifest.json");
const pkg = await readJson("package.json");
const packageLock = await readJson("package-lock.json");
const artifactStats = {};

for (const artifact of requiredArtifacts) {
  const artifactPath = resolve(projectRoot, artifact);
  const info = await stat(artifactPath);
  const minSize = minimumArtifactSizes[artifact];
  if (!info.isFile()) {
    throw new Error(`Release artifact is not a file: ${artifact}`);
  }
  if (info.size < minSize) {
    throw new Error(`Release artifact is unexpectedly small: ${artifact} (${info.size} bytes)`);
  }
  artifactStats[artifact] = info.size;
}

assertEqual(manifest.id, pkg.name, "manifest id must match package name");
assertEqual(manifest.version, pkg.version, "manifest version must match package version");
assertEqual(packageLock.name, pkg.name, "package-lock name must match package name");
assertEqual(packageLock.version, pkg.version, "package-lock version must match package version");
assertEqual(pkg.main, "main.js", "package main must point at main.js");

for (const field of ["id", "name", "version", "minAppVersion", "description", "author"]) {
  if (typeof manifest[field] !== "string" || manifest[field].trim().length === 0) {
    throw new Error(`manifest.${field} must be a non-empty string`);
  }
}

if (manifest.id !== "documents-bundle") {
  throw new Error(`Unexpected plugin id: ${manifest.id}`);
}
if (manifest.name !== "Documents Bundle") {
  throw new Error(`Unexpected plugin display name: ${manifest.name}`);
}
if (manifest.isDesktopOnly !== false) {
  throw new Error("manifest.isDesktopOnly must remain false while mobile fallback paths are supported.");
}

const mainJs = await readFile(resolve(projectRoot, "main.js"), "utf8");
if (!mainJs.startsWith("/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD */")) {
  throw new Error("main.js does not look like the esbuild production bundle.");
}
if (!mainJs.includes("documents-bundle-native-bundle")) {
  throw new Error("main.js does not include the native File Explorer bundle marker.");
}
if (!mainJs.includes("documents-bundle-native-bundle-children")) {
  throw new Error("main.js does not include the native File Explorer internals hiding marker.");
}
if (!mainJs.includes("documents-bundle")) {
  throw new Error("main.js does not include the plugin id.");
}

const styles = await readFile(resolve(projectRoot, "styles.css"), "utf8");
if (!styles.includes(".documents-bundle-native-bundle-title")) {
  throw new Error("styles.css does not include native File Explorer marker styles.");
}
if (!styles.includes(".documents-bundle-native-bundle-children")) {
  throw new Error("styles.css does not include native File Explorer internals hiding styles.");
}

console.log(JSON.stringify({
  releaseValidation: true,
  plugin: {
    id: manifest.id,
    name: manifest.name,
    version: manifest.version,
    minAppVersion: manifest.minAppVersion,
    isDesktopOnly: manifest.isDesktopOnly
  },
  artifacts: artifactStats
}, null, 2));

async function readJson(relativePath) {
  return JSON.parse(await readFile(resolve(projectRoot, relativePath), "utf8"));
}

function assertEqual(actual, expected, message) {
  if (actual !== expected) {
    throw new Error(`${message}: expected ${JSON.stringify(expected)}, got ${JSON.stringify(actual)}`);
  }
}
